name: Send mail
  if: commit()
  uses: dawidd6/action-send-mail@v2
  with:
    # mail server settings
    server_address: smtp.gmail.com
    server_port: 465
    # user credentials
    username: ${{ secrets.EMAIL_USERNAME }}
    password: ${{ secrets.EMAIL_PASSWORD }}
    # email subject
    subject: ${{ github.job }} Trabajo de ${{ github.repository }} esta ${{ job.status }}
    # email body as text
    body: ${{ github.job }} el fluido de trabajo ${{ github.workflow }} de ${{ github.repository }} tiene un ${{ job.status }}
    # comma-separated string, send email to
    to: jaime.sanchez.hita@kyndryl.com
    # from email name
    from: Notificaciones
